### PR TITLE
various CGI "fixes"

### PR DESCRIPTION
**Pull request by the-eater**
This patch looks for new query string parameters in the remapped path and adds those properly to the remapped request

### CODE REVIEW

**Comment by the-eater** [comment]
hmm, are you sure you want to allow remapping to outside the gophor root? :thinking:

**Comment by the-eater** [comment]
All this code is open for discussion btw, I just wrote in a way the "issues" would be fixed :)

**Comment by grufwub** [comment]
> hmm, are you sure you want to allow remapping to outside the gophor root? thinking

as discussed, this was me trying out some things in development though something i was wrong in assuming :).

am reading through the other changes now :+1:

**Comment by grufwub** [comment]
Okay I am going to merge this in and make any changes on top. Thank you again :D

**Pull request merged**
